os: linux
dist: focal
language: python
python:
  - "2.7"
  - "3.6"
  - "3.9"

addons:
  apt:
    packages:
    - wget
    - libgmp-dev
    - libffi6
    - libc6:i386
    - ocl-icd-libopencl1

before_install:
 # install Futhark
 - wget http://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
 - tar xf futhark-nightly-linux-x86_64.tar.xz
 - (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)

install:
  - futhark c --library test.fut
  - python setup.py install
  - build_futhark_ffi test

script:
  - python test.py
